services:
  postgres:
    image: postgres:17-alpine
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.3'  
    # ðŸŒŸ ConfiguraciÃ³n para chequear si Postgres estÃ¡ listo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  redis:
    image: redis:8.4.0-alpine
    container_name: my_radis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: '0.3'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    container_name: export_backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PORT=${BACKEND_PORT}
      - REDIS_URL=redis://redis:6379
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    extra_hosts:
      # Hace que 'host.docker.internal' resuelva a la IP del host/gateway. (Linux / Windows)
      - "host.docker.internal:host-gateway" 
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    deploy:
      resources:
        limits:
          cpus: '0.3'   
    # ðŸ’¥ EJECUCIÃ“N CRÃTICA: Inicializa la DB y luego arranca la app
    # 1. npx prisma migrate reset --force: Resetea la DB y aplica las migraciones (uso en desarrollo)
    # 2. && npm run dev: Arranca el servidor Express/Node
    #command: sh -c "npx prisma migrate reset --force && npm run dev"
    command: >
      sh -c "
        npx prisma db push --force-reset --accept-data-loss &&
        npx ts-node prisma/seed.ts || true &&
        npm run dev
      "
  
  frontend:
    build: ./frontend
    container_name: export_frontend
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - PORT=${FRONTEND_PORT}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    deploy:
      resources:
        limits:
          cpus: '0.3'   
    command: sh -c "rm -rf .next &&npm install && npm run dev -- -H 0.0.0.0 -p ${FRONTEND_PORT}"

volumes:
  postgres_data:
  redis_data: