services:
  postgres:
    image: postgres:17-alpine
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # üåü Configuraci√≥n para chequear si Postgres est√° listo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  redis:
    image: redis:8.4.0-alpine
    container_name: my_radis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    container_name: export_backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    extra_hosts:
      # Hace que 'host.docker.internal' resuelva a la IP del host/gateway. (Linux / Windows)
      - "host.docker.internal:host-gateway" 
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules 
    # üí• EJECUCI√ìN CR√çTICA: Inicializa la DB y luego arranca la app
    # 1. npx prisma migrate reset --force: Resetea la DB y aplica las migraciones (uso en desarrollo)
    # 2. && npm run dev: Arranca el servidor Express/Node
    command: sh -c "npx prisma db push && npx prisma db seed && npm run dev"

  frontend:
    build: ./frontend
    container_name: export_frontend
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - PORT=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run dev -- -H 0.0.0.0 -p ${FRONTEND_PORT}"

volumes:
  postgres_data:
  redis_data: